sensor:
  - platform: snmp
    name: Firebrick SNMP WAN1 In
    host: 192.168.2.1
    baseoid: 1.3.6.1.2.1.2.2.1.10.4104
    community: "public"
    version: "2c"
    state_class: total_increasing
    icon: mdi:cloud-download
    unit_of_measurement: "B"

  - platform: snmp
    name: Firebrick SNMP WAN1 Out
    host: 192.168.2.1
    baseoid: 1.3.6.1.2.1.2.2.1.16.4104
    community: "public"
    version: "2c"
    state_class: total_increasing
    icon: mdi:cloud-download
    unit_of_measurement: "B"

  - platform: derivative
    name: Firebrick SNMP WAN1 In Derivative
    source: sensor.firebrick_snmp_wan1_in
    unit_time: "s"
    round: 2

  - platform: derivative
    name: Firebrick SNMP WAN1 Out Derivative
    source: sensor.firebrick_snmp_wan1_out
    unit_time: "s"
    round: 2

template:
  - sensor:
      - name: Firebrick SNMP WAN1 RX Rate
        unique_id: fb-snmp-wan1-rx-rate
        unit_of_measurement: Mbit/s
        icon: mdi:cloud-download
        state_class: measurement
        state: >-
          {{
            states('sensor.firebrick_snmp_wan1_in_derivative')
            | multiply(8)
            | multiply(0.000001)
            | round(5)
          }}

      - name: Firebrick SNMP WAN1 TX Rate
        unique_id: fb-snmp-wan1-tx-rate
        unit_of_measurement: Mbit/s
        icon: mdi:cloud-download
        state_class: measurement
        state: >-
          {{
            states('sensor.firebrick_snmp_wan1_out_derivative')
            | multiply(8)
            | multiply(0.000001)
            | round(5)
          }}
