sensor:
  - platform: rest
    name: Electricity consumption
    resource_template: >-
      {% set mpan = 'XXX' %}
      {% set serial = 'YYY' %}
      {% set date = (now() - timedelta(days = 1)).strftime('%Y-%m-%d') %}
      https://api.octopus.energy/v1/electricity-meter-points/{{ mpan }}/meters/{{ serial }}/consumption/?period_from={{ date + 'T00:00:00' }}&period_to={{ date + 'T23:59:59' }}
    headers:
      Authorization: !secret octopus_auth
    value_template: "{{ value_json.results | sum(attribute='consumption') | round(3) }}"
    unit_of_measurement: 'kWh'
    json_attributes:
      - "results"

  - platform: rest
    name: Agile rates today
    resource_template: >-
      {% set region = 'A' %}
      {% set date = utcnow().strftime('%Y-%m-%d') %}
      https://api.octopus.energy/v1/products/AGILE-18-02-21/electricity-tariffs/E-1R-AGILE-18-02-21-{{ region }}/standard-unit-rates/?period_from={{ date + 'T00:00:00Z' }}&period_to={{ date + 'T23:59:59Z' }}
    value_template: "{{ as_timestamp(value_json.results[-1].valid_from) | timestamp_custom('%Y-%m-%d') }}"
    json_attributes:
      - "results"

  - platform: rest
    name: Agile rates tomorrow
    resource_template: >-
      {% set region = 'A' %}
      {% set date = (utcnow() + timedelta(days = 1)).strftime('%Y-%m-%d') %}
      https://api.octopus.energy/v1/products/AGILE-18-02-21/electricity-tariffs/E-1R-AGILE-18-02-21-{{ region }}/standard-unit-rates/?period_from={{ date + 'T00:00:00Z' }}&period_to={{ date + 'T23:59:59Z' }}
    value_template: "{{ as_timestamp(value_json.results[-1].valid_from) | timestamp_custom('%Y-%m-%d') }}"
    json_attributes:
      - "results"

  - platform: template
    sensors:
      agile_min_rate:
        friendly_name: Agile minimum rate
        icon_template: mdi:flash
        value_template: "{{ '%.2f' | format((state_attr('sensor.agile_rates_today', 'results') | sort(attribute='value_inc_vat') | first).value_inc_vat) }}"
        unit_of_measurement: 'p/kWh'
        attribute_templates:
          valid_from: "{{ (state_attr('sensor.agile_rates_today', 'results') | sort(attribute='value_inc_vat') | first).valid_from }}"
          valid_to: "{{ (state_attr('sensor.agile_rates_today', 'results') | sort(attribute='value_inc_vat') | first).valid_to }}"

      agile_avg_rate:
        friendly_name: Agile average rate
        value_template: "{{ '%.2f' | format(state_attr('sensor.agile_rates_today', 'results') | sum(attribute='value_inc_vat') / 48) }}"
        unit_of_measurement: 'p/kWh'

      agile_current_rate:
        friendly_name: Agile current rate
        icon_template: mdi:flash
        value_template: >-
          {% set from = ((utcnow().timestamp() / 1800) | round(0, 'floor') | int * 1800) | timestamp_custom('%Y-%m-%dT%H:%M:%SZ', False) %}
          {{ '%.2f' | format((state_attr('sensor.agile_rates_today', 'results') | selectattr('valid_from', 'eq', from) | first).value_inc_vat) }}
        unit_of_measurement: 'p/kWh'
        attribute_templates:
          valid_from: >-
            {% set from = ((utcnow().timestamp() / 1800) | round(0, 'floor') | int * 1800) | timestamp_custom('%Y-%m-%dT%H:%M:%SZ', False) %}
            {{ (state_attr('sensor.agile_rates_today', 'results') | selectattr('valid_from', 'eq', from) | first).valid_from }}
          valid_to: >-
            {% set from = ((utcnow().timestamp() / 1800) | round(0, 'floor') | int * 1800) | timestamp_custom('%Y-%m-%dT%H:%M:%SZ', False) %}
            {{ (state_attr('sensor.agile_rates_today', 'results') | selectattr('valid_from', 'eq', from) | first).valid_to }}

      agile_next_rate:
        friendly_name: Agile next rate
        icon_template: mdi:flash
        value_template: >-
          {% set from = (((utcnow().timestamp() / 1800) | round(0, 'floor') | int * 1800) + 30 * 60) | timestamp_custom('%Y-%m-%dT%H:%M:%SZ', False) %}
          {{ '%.2f' | format((state_attr('sensor.agile_rates_today', 'results') | selectattr('valid_from', 'eq', from) | first).value_inc_vat) }}
        unit_of_measurement: 'p/kWh'
        attribute_templates:
          valid_from: >-
            {% set from = (((utcnow().timestamp() / 1800) | round(0, 'floor') | int * 1800) + 30 * 60) | timestamp_custom('%Y-%m-%dT%H:%M:%SZ', False) %}
            {{ (state_attr('sensor.agile_rates_today', 'results') | selectattr('valid_from', 'eq', from) | first).valid_from }}
          valid_to: >-
            {% set from = (((utcnow().timestamp() / 1800) | round(0, 'floor') | int * 1800) + 30 * 60) | timestamp_custom('%Y-%m-%dT%H:%M:%SZ', False) %}
            {{ (state_attr('sensor.agile_rates_today', 'results') | selectattr('valid_from', 'eq', from) | first).valid_to }}

      agile_prev_rate:
        friendly_name: Agile previous rate
        icon_template: mdi:flash
        value_template: >-
          {% set from = (((utcnow().timestamp() / 1800) | round(0, 'floor') | int * 1800) - 30 * 60) | timestamp_custom('%Y-%m-%dT%H:%M:%SZ', False) %}
          {{ '%.2f' | format((state_attr('sensor.agile_rates_today', 'results') | selectattr('valid_from', 'eq', from) | first).value_inc_vat) }}
        unit_of_measurement: 'p/kWh'
        attribute_templates:
          valid_from: >-
            {% set from = (((utcnow().timestamp() / 1800) | round(0, 'floor') | int * 1800) - 30 * 60) | timestamp_custom('%Y-%m-%dT%H:%M:%SZ', False) %}
            {{ (state_attr('sensor.agile_rates_today', 'results') | selectattr('valid_from', 'eq', from) | first).valid_from }}
          valid_to: >-
            {% set from = (((utcnow().timestamp() / 1800) | round(0, 'floor') | int * 1800) - 30 * 60) | timestamp_custom('%Y-%m-%dT%H:%M:%SZ', False) %}
            {{ (state_attr('sensor.agile_rates_today', 'results') | selectattr('valid_from', 'eq', from) | first).valid_to }}